name: "Snyk C++ Scan"

on:
  push:
    branches:
      - 'demo*'  # Include any branch starting with demo

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Scan'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1

      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          snyk auth ${SNYK_TOKEN} --auth-type=token 
          
      # Run Snyk OS (C++ with the --unmanaged option)
      - name: Run Snyk OS
        run: |
          snyk test --project-name="GH_ACTION_C++" --unmanaged --print-deps --severity-threshold=critical
        continue-on-error: true
